legend = ["LAT_ACCEL_FACTOR", "MAX_LAT_ACCEL_MEASURED", "FRICTION"]
"MAZDA3" = "CX9_2021"
"MAZDA6" = "CX9_2021"
"CX5" = "CX9_2021"
"CX5_2022" = "CX9_2021"
"CX9" = "CX9_2021"

"DODGE_DURANGO" = "PACIFICA_2020"

"ALPHARD_TSS2" = "SIENNA"
"PRIUS_V" = "PRIUS"
"LEXUS_IS" = "LEXUS_NX"
"LEXUS_CTH" = "LEXUS_NX"
"LEXUS_ES" = "CAMRY"
"LEXUS_RC" = "LEXUS_NX_TSS2"
"LEXUS_LC_TSS2" = "LEXUS_NX_TSS2"

"KIA_OPTIMA_G4" = "SONATA"
"KIA_OPTIMA_G4_FL" = "SONATA"
"KIA_OPTIMA_H" = "SONATA"
"KIA_OPTIMA_H_G4_FL" = "SONATA"
"KIA_FORTE" = "SONATA"
"KIA_CEED" = "SONATA"
"KIA_SELTOS" = "SONATA"
"KIA_NIRO_PHEV" = "KIA_NIRO_EV"
"KIA_NIRO_PHEV_2022" = "KIA_NIRO_EV"
"KIA_NIRO_HEV_2021" = "KIA_NIRO_EV"
"VELOSTER" = "SONATA_LF"
"KONA" = "KONA_EV"
"KONA_HEV" = "KONA_EV"
"KONA_EV_2022" = "KONA_EV"
"IONIQ" = "IONIQ_PHEV_2019"
"IONIQ_HEV_2022" = "IONIQ_PHEV_2019"
"IONIQ_EV_2020" = "IONIQ_PHEV_2019"
"ELANTRA" = "SONATA_LF"
"ELANTRA_GT_I30" = "SONATA_LF"
"ELANTRA_HEV_2021" = "SONATA"
"TUCSON" = "SANTA_FE"
"SANTA_FE_2022" = "SANTA_FE_HEV_2022"
"KIA_K5_HEV_2020" = "KIA_K5_2021"
"KIA_STINGER_2022" = "KIA_STINGER"
"GENESIS_G90" = "GENESIS_G70"
"GENESIS_G80" = "GENESIS_G70"
"GENESIS_G70_2020" = "SONATA"

"FREED" = "ODYSSEY"
"CRV_EU" = "CRV"
"CIVIC_BOSCH_DIESEL" = "CIVIC_BOSCH"
"HONDA_E" = "CIVIC_BOSCH"
"ODYSSEY_CHN" = "ODYSSEY"

"BUICK_LACROSSE" = "VOLT"
"BUICK_REGAL" = "VOLT"
"ESCALADE_ESV" = "VOLT"
"CADILLAC_ATS" = "VOLT"
"MALIBU" = "VOLT"
"HOLDEN_ASTRA" = "VOLT"

"SKODA_FABIA_MK4" = "GOLF_MK7"
"SKODA_OCTAVIA_MK3" = "SKODA_SUPERB_MK3"
"SKODA_SCALA_MK1" = "SKODA_SUPERB_MK3"
"SKODA_KODIAQ_MK1" = "SKODA_SUPERB_MK3"
"SKODA_KAROQ_MK1" = "SKODA_SUPERB_MK3"
"SKODA_KAMIQ_MK1" = "SKODA_SUPERB_MK3"
"CRAFTER_MK2" = "TIGUAN_MK2"
"TROC_MK1" = "TIGUAN_MK2"
"TCROSS_MK1" = "TIGUAN_MK2"
"TOURAN_MK2" = "TIGUAN_MK2"
"TRANSPORTER_T61" = "TIGUAN_MK2"
"AUDI_Q2_MK1" = "TIGUAN_MK2"
"TAOS_MK1" = "TIGUAN_MK2"
"POLO_MK6" = "GOLF_MK7"
"SEAT_LEON_MK3" = "GOLF_MK7"
"SEAT_ATECA_MK1" = "GOLF_MK7"

"CROSSTREK_HYBRID" = "IMPREZA_2020"
"FORESTER_HYBRID" = "IMPREZA_2020"
"LEGACY" = "OUTBACK"

# Old subarus don't have much data guessing it's like low torque impreza"
"OUTBACK_PREGLOBAL_2018" = "IMPREZA"
"OUTBACK_PREGLOBAL" = "IMPREZA"
"FORESTER_PREGLOBAL" = "IMPREZA"
"LEGACY_PREGLOBAL" = "IMPREZA"
"ASCENT" = "FORESTER"
