name: 'openpilot env setup, with retry on failure'

inputs:
  git_lfs:
    description: 'Whether or not to pull the git lfs'
    required: false
    default: 'true'

env:
  SLEEP_TIME: 30 # Time to sleep between retries

runs:
  using: "composite"
  steps:
    - id: setup1
      uses: ./.github/workflows/setup
      continue-on-error: true
      with:
        git_lfs: ${{ inputs.git_lfs }}
        is_retried: true
    - if: steps.setup1.outcome == 'failure'
      shell: bash
      run: sleep ${{ env.SLEEP_TIME }}
    - id: setup2
      if: steps.setup1.outcome == 'failure'
      uses: ./.github/workflows/setup
      continue-on-error: true
      with:
        git_lfs: ${{ inputs.git_lfs }}
        is_retried: true
    - if: steps.setup2.outcome == 'failure'
      shell: bash
      run: sleep ${{ env.SLEEP_TIME }}
    - id: setup3
      if: steps.setup2.outcome == 'failure'
      uses: ./.github/workflows/setup
      with:
        git_lfs: ${{ inputs.git_lfs }}
        is_retried: true