name: prebuilt
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  DOCKER_GHCR_LOGIN: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  BUILD: selfdrive/test/docker_build.sh prebuilt

jobs:
  build_prebuilt:
    name: build prebuilt
    runs-on: ubuntu-20.04
    if: github.repository == 'commaai/openpilot'
    env:
      PUSH_IMAGE: true
    steps:
    - name: Wait for green check mark
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: lewagon/wait-on-check-action@e2558238c09778af25867eb5de5a3ce4bbae3dcd
      with:
        ref: master
        wait-interval: 30
        running-workflow-name: 'build prebuilt'
        check-regexp: ^((?!.*(build master-ci).*).)*$
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build and Push docker image
      run: |
        $DOCKER_GHCR_LOGIN
        eval "$BUILD"
